apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-app
  template:
    metadata:
      labels:
        app: pgadmin-app
    spec:
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: data-pgadmin
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4
        envFrom:
          - configMapRef:
              name: pgadmin-cofigmap
          - secretRef:
              name: secret-pgadmin
        ports:
        - containerPort: 80
          name: pgadmin-port
        volumeMounts:
          - name: pgadmin-data
            mountPath: /var/lib/pgadmin
        resources:
          requests:
            memory: "265Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-cofigmap
data:
  PGADMIN_PORT: "80"
  PGADMIN_CONFIG_SERVER_MODE: "False"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: user@domain.com
  PGADMIN_DEFAULT_PASSWORD: password
  

  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pgadmin
spec:
  # storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-dep
spec:
  ports:
  - port: 80
    protocol: TCP
    name: pgadmin-port
  selector:
    app: pgadmin-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  tls:
  - hosts:
    - pgadmin.home.local
    secretName: pgadmin-tls
  ingressClassName: nginx
  rules:
  - host: pgadmin.home.local
    http:
      paths:
      - backend:
          service:
            name: pgadmin-dep
            port:
              number: 80
        path: /
        pathType: Prefix